### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by fahamjv** [genki-angel/discord-data-reader-app#1]
after `cd discord-data-reader-vue && npx vue-cli-service build --dest ../resources/ && cd .. && neu build` it get's this error `npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-cli-service - Not found
npm ERR! 404 
npm ERR! 404  'vue-cli-service@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/batman/.npm/_logs/2022-03-29T00_48_38_786Z-debug.log
`

**Comment by genki-angel** [comment]
This can be solved by running `npm install` in the submodule folder "discord-data-reader-vue".
README.md had been updated to make it more clear 5062a4aab11a5fee5c817a6ba14489f1677a1aec
